# -*- coding: utf-8 -*-
"""Nairaland_pol_section

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IXLdUUVUDpAm7s-fHdw5jCcDqYSI6cV8
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
url = "https://www.nairaland.com/politics"
links = []
for i in range(0,10):
    if i == 0:
        url_page = url
    else:
        url_page = str(url) + "/{}".format(i)
    try:
        page = requests.get(url_page).text
    except:
        pass
    soup = BeautifulSoup(page,"lxml")
    # post = soup.find('body')
    url_links = soup.find_all('a')
    for url in url_links:
        if url.has_attr("href") and url["href"].startswith("http"):
            links.append(url["href"])
posts = []
posts_link= []

for link in links:
    try:
        page = requests.get(link).text
    except:
        pass
    soup = BeautifulSoup(page,"lxml")

    for comment in soup.find_all("div", class_="narrow"):
        posts.append(comment.text)
        posts_link.append(link)

df=pd.DataFrame({"Comments": posts, "links":posts_link})
df.to_csv('Nairaland_df.csv')

